#!/bin/bash

# Switch environment to 'vm' and insert VM packages
sed -e 's/^\s*environment=ks/environment=vm/
/^\@server-policy/a \
@desktop \
eclipse \
firefox \

/^configure_repos()/ {
	:a
	  s/.*//
	  N
	/\n}/!ba
	  r vm/vm_insert.sh
	  d
}
' $1 > $2
